Fixes
CanonicalLtd/aws-marketplace-ubuntu-scraper pull request #6
Opened 2021-12-13 18:02 UTC by toabctl

2021-12-14 09:45 UTC, toabctl commented
Tested with:
1) generating the quickstart_entries.json file with:
```
python -m aws_marketplace_ubuntu_scraper quicklaunch --iam-account-id=XXX --iam-username=XXX --iam-password="XXX" --no-headless
```
2) generating the report with:
```
python -m aws_marketplace_ubuntu_scraper report
```

that results in:
```
$ python -m aws_marketplace_ubuntu_scraper report
Checking region af-south-1 ...
Checking region ap-east-1 ...
Checking region ap-northeast-1 ...
Checking region ap-northeast-2 ...
Checking region ap-northeast-3 ...
Checking region ap-south-1 ...
Checking region ap-southeast-1 ...
Checking region ap-southeast-2 ...
Checking region ap-southeast-3 ...
Checking region ca-central-1 ...
Checking region eu-central-1 ...
Checking region eu-north-1 ...
Checking region eu-south-1 ...
Checking region eu-west-1 ...
Checking region eu-west-2 ...
Checking region eu-west-3 ...
Checking region me-south-1 ...
Checking region sa-east-1 ...
Checking region us-east-1 ...
Checking region us-east-2 ...
Checking region us-west-1 ...
Checking region us-west-2 ...
+----------------+---------+-------+----------+-----------------------+-----------------------+--------------+
|     Region     | Release |  Arch | Position |     Quickstart AMI    |      Streams AMI      | Needs update |
+----------------+---------+-------+----------+-----------------------+-----------------------+--------------+
|   us-west-2    |  20.04  | arm64 |    8     | ami-078278691222aee06 | ami-078278691222aee06 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-2    |  20.04  | amd64 |    8     | ami-0892d3c7ee96c0bf7 | ami-0892d3c7ee96c0bf7 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-2    |  18.04  | arm64 |    9     | ami-08d20da2261ebe2ec | ami-08d20da2261ebe2ec |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-2    |  18.04  | amd64 |    9     | ami-074251216af698218 | ami-074251216af698218 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-2    |  16.04  | arm64 |    41    | ami-08305dd8ab642ad8c | ami-08305dd8ab642ad8c |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-2    |  16.04  | amd64 |    41    | ami-0688ba7eeeeefe3cd | ami-0688ba7eeeeefe3cd |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  20.04  | arm64 |    5     | ami-039da1612f6f41296 | ami-039da1612f6f41296 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  20.04  | amd64 |    5     | ami-01f87c43e618bf8f0 | ami-01f87c43e618bf8f0 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  18.04  | arm64 |    6     | ami-0f561e14031ed52d3 | ami-0f561e14031ed52d3 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  18.04  | amd64 |    6     | ami-009726b835c24a3aa | ami-009726b835c24a3aa |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  16.04  | arm64 |    36    | ami-06d79d5316d395362 | ami-06d79d5316d395362 |    False     |
|                |         |       |          |                       |                       |              |
|   us-west-1    |  16.04  | amd64 |    36    | ami-0454207e5367abf01 | ami-0454207e5367abf01 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  20.04  | arm64 |    8     | ami-02af65b2d1ebdfafc | ami-02af65b2d1ebdfafc |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  20.04  | amd64 |    8     | ami-0fb653ca2d3203ac1 | ami-0fb653ca2d3203ac1 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  18.04  | arm64 |    28    | ami-023d39cbc16614424 | ami-023d39cbc16614424 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  18.04  | amd64 |    28    | ami-03a0c45ebc70f98ea | ami-03a0c45ebc70f98ea |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  16.04  | arm64 |    40    | ami-0b76100074ce446d4 | ami-0b76100074ce446d4 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-2    |  16.04  | amd64 |    40    | ami-05803413c51f242b7 | ami-05803413c51f242b7 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  20.04  | arm64 |    8     | ami-0b49a4a6e8e22fa16 | ami-0b49a4a6e8e22fa16 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  20.04  | amd64 |    8     | ami-04505e74c0741db8d | ami-04505e74c0741db8d |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  18.04  | arm64 |    9     | ami-0a940cb939351ccca | ami-0a940cb939351ccca |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  18.04  | amd64 |    9     | ami-0e472ba40eb589f49 | ami-0e472ba40eb589f49 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  16.04  | arm64 |    41    | ami-04b3c39a8a1c62b76 | ami-04b3c39a8a1c62b76 |    False     |
|                |         |       |          |                       |                       |              |
|   us-east-1    |  16.04  | amd64 |    41    | ami-0b0ea68c435eb488d | ami-0b0ea68c435eb488d |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  20.04  | arm64 |    5     | ami-0e9fbe8acb00ab545 | ami-0e9fbe8acb00ab545 |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  20.04  | amd64 |    5     | ami-090006f29ecb2d79a | ami-090006f29ecb2d79a |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  18.04  | arm64 |    9     | ami-0399e2debd94407c8 | ami-0399e2debd94407c8 |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  18.04  | amd64 |    9     | ami-07b5a89195c6932c8 | ami-07b5a89195c6932c8 |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  16.04  | arm64 |    38    | ami-08bf1084c0b9a3361 | ami-08bf1084c0b9a3361 |    False     |
|                |         |       |          |                       |                       |              |
|   sa-east-1    |  16.04  | amd64 |    38    | ami-0a729bdc1acf7528b | ami-0a729bdc1acf7528b |    False     |
|                |         |       |          |          [...]

2021-12-16 13:21 UTC, j5awry approved these changes

2021-12-16 13:21 UTC, j5awry commented
I'll let Phil take a look before merging, but LGTM!

2021-12-20 12:22 UTC, philroche requested changes
Looks good. A few small change requests

2021-12-20 12:22 UTC, philroche commented on aws_marketplace_ubuntu_scraper.py
> +    for region in data:
Can we sort the regions here please?

2021-12-20 12:22 UTC, philroche commented on aws_marketplace_ubuntu_scraper.py
> +    cmd = ['/snap/bin/sstream-query-cpc', '--max=1',
We need to add the simplesteams snap as a dependency in the readme. Also we should be using 

```
/snap/bin/simplestreams.sstream-query
```

2022-01-03 10:19 UTC, philroche requested changes

2022-01-03 10:19 UTC, philroche commented on aws_marketplace_ubuntu_scraper.py
> +def report(scraper_data):
Can you change this to `quicklaunch-report` so we can have an equivalent report for the marketplace scraping?

2022-01-04 12:02 UTC, toabctl commented on aws_marketplace_ubuntu_scraper.py
> +    for region in data:
The entries in quickstart_entries.json are already sorted. But sorted anyway . So Fixed.

2022-01-04 12:02 UTC, toabctl commented on aws_marketplace_ubuntu_scraper.py
> +    cmd = ['/snap/bin/sstream-query-cpc', '--max=1',
Fixed

2022-01-04 12:02 UTC, toabctl commented on aws_marketplace_ubuntu_scraper.py
> +def report(scraper_data):
Fixed

2022-01-05 08:42 UTC, philroche approved these changes
Thank you for those changes. +1

2022-01-05 09:08 UTC, merged